### ISSUE TITLE
cmd目录下的phonedata.exe不能用

### ISSUE THREAD

**Issue by CNMan** [xluohome/phonedata#6]
```bat
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

e:\Backup\go\src\github.com\xluohome\phonedata\cmd>go run phonedata.go 1388888
PhoneNum: 1388888
AreaZone: 0871
CardType: 中国移动
City: 昆明
ZipCode: 650000
Province: 云南

e:\Backup\go\src\github.com\xluohome\phonedata\cmd>phonedata 1388888
panic: open C:/Users/xluo/Documents/goproject/src/github.com/xluohome/phonedata/phone.dat: The system cannot find the path specified.

goroutine 1 [running]:
github.com/xluohome/phonedata.init.1()
        C:/Users/xluo/Documents/goproject/src/github.com/xluohome/phonedata/phonedata.go:58 +0x152
github.com/xluohome/phonedata.init()
        C:/Users/xluo/Documents/goproject/src/github.com/xluohome/phonedata/phonedata.go:185 +0x12e
main.init()
        C:/Users/xluo/Documents/goproject/src/github.com/xluohome/phonedata/cmd/phonedata.go:23 +0x55

e:\Backup\go\src\github.com\xluohome\phonedata\cmd>
```
依赖编译时`phone.dat`的路径，建议删除可执行文件，readme里添加编译说明。

**Comment by xluohome** [comment]
感谢，提交 issue。

phone.dat 的路径可以使用环境变量： PHONE_DATA_DIR 指定；

**Comment by xluohome** [comment]
README.md 已经修改示例描述文字。
